In [1]:
import matplotlib.pyplot as plt
import time
import datetime as dt
import pickle
import numpy as np
import borrador
from __future__ import division
from auxiliar_functions import *
import tfe


In [2]:
frame = pd.read_csv('/home/cata/Documentos/Datois/etapas_2013_abril_allyearsids_10_100000.csv')


In [3]:
frame = frame_config(frame)

In [4]:
#frame.drop(frame.columns[[2,3,4,5,9,10,11,14,15,16]], axis=1, inplace=True)
frame.head()

tiempo_subida       id  x_subida  y_subida tipo_transporte  \
23 2013-04-14 06:45:44  1132106    348108   6289153             BUS   
22 2013-04-14 07:51:52  1132106    346751   6299389             BUS   
21 2013-04-14 19:56:47  1132106    351368   6302559             BUS   
20 2013-04-14 20:15:25  1132106    346713   6299427             BUS   
19 2013-04-15 21:04:59  1132106    348103   6289191             BUS   

   serviciosentidovariante tipo_dia  nviaje  netapa  x_bajada  \
23                T203 00R  DOMINGO       1       1    346818   
22                T502 00I  DOMINGO       2       1    351363   
21                T502 00R  DOMINGO       3       1    346763   
20                T203 00I  DOMINGO       3       2    348095   
19                T206 00R  LABORAL       4       1    346844   

          ...              par_bajada zona_subida zona_bajada adulto  weekday  \
23        ...          E-20-190-SN-40         328         307      0        6   
22        ...           T-15-135-PO-5         307         188      0        6   
21        ...           T-4-19-NS-100         188          55      0        6   
20        ...          T-24-205-NS-20         307         348      0        6   
19        ...          T-20-190-SN-35         328         309      0        0   

    lat_subida  lat_bajada  long_subida  long_bajada  diferencia_tiempo  
23  -33.526277  -33.526277   -70.635551   -70.647786    0 days 00:00:00  
22  -33.434116  -33.434116   -70.648104   -70.598251    0 days 01:06:08  
21  -33.405971  -33.405971   -70.598379   -70.648651    0 days 12:04:55  
20  -33.433463  -33.433463   -70.649060   -70.635944    0 days 00:18:38  
19  -33.526277  -33.526277   -70.635551   -70.647429    1 days 00:49:34  

[5 rows x 23 columns]

In [5]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 23 to 99994
Data columns (total 23 columns):
tiempo_subida              100000 non-null datetime64[ns]
id                         100000 non-null int64
x_subida                   99224 non-null float64
y_subida                   99224 non-null float64
tipo_transporte            100000 non-null object
serviciosentidovariante    98074 non-null object
tipo_dia                   100000 non-null object
nviaje                     100000 non-null int64
netapa                     100000 non-null int64
x_bajada                   86774 non-null float64
y_bajada                   86774 non-null float64
tiempo_bajada              86774 non-null object
par_subida                 99195 non-null object
par_bajada                 86767 non-null object
zona_subida                99180 non-null float64
zona_bajada                86764 non-null float64
adulto                     86774 non-null float64
weekday                    100000 non-

In [6]:
test_sequence_5 = frame.query('id==1261466')
test_sequence_1187 = frame.query('id==50264508')
test_sequence_0 = frame.query('id==1132106')
test_sequence_9 = frame.query('id==1355530')
test_sequence_2168 = frame.query('id==59460077')
test_sequence_3696 = frame.query('id==68660100')
test_sequence_4150= frame.query('id==70321252')

In [7]:
test_sequence = test_sequence_0
[test_sequence_s ,test_sequence_fds] = tfe.split_sequence_by_weekdays(test_sequence)

In [8]:
shortest_activities_s = tfe.get_mean_shortests_activity_length(test_sequence_s)
longest_activities_s = tfe.get_mean_longest_activity_length(test_sequence_s)
shortest_activities_fds = tfe.get_mean_shortests_activity_length(test_sequence_fds)
longest_activities_fds = tfe.get_mean_longest_activity_length(test_sequence_fds)

In [9]:
print str(shortest_activities_s) + " , " + str(shortest_activities_fds)
print str(longest_activities_s) + " , " + str(longest_activities_fds)

772 , 66
0 days 09:52:16.400000 , 1 days 23:16:58


In [10]:
latlong1 = (test_sequence_fds['lat_subida'][0],test_sequence_fds['long_subida'][0])
latlong2 = (test_sequence_fds['lat_bajada'][0],test_sequence_fds['long_bajada'][0])

In [11]:
tfe.get_traveled_distance(test_sequence)

221.22859034150613

In [12]:
tfe.get_maximum_travel_distance(test_sequence)

16.64618851242621

In [13]:
tfe.get_minimum_travel_distance(test_sequence)

1.136515222708523

In [14]:
tfe.get_percentage_bus_exclusive_days(test_sequence)

100.0

In [15]:
tfe.get_percentage_rail_exclusive_days(test_sequence)

0.0

In [16]:
tfe.get_card_type(test_sequence)

0

In [17]:
tfe.get_n_days_traveled(test_sequence)

7

In [18]:
tfe.get_n_trips_per_day(test_sequence)

[3, 1, 2, 2, 2, 0, 1, 2]

In [19]:
tfe.get_mean_start_time_first_trip(test_sequence)

33061

In [20]:
tfe.get_mean_start_time_last_trip(test_sequence)

67229

In [21]:
tfe.get_percentage_different_last_origin(test_sequence)

57.14285714285714

In [22]:
tfe.get_percentage_different_first_origin(test_sequence)

42.857142857142854

In [23]:
tfe.get_n_different_locations(test_sequence)

5

In [24]:
tfe.get_radius_of_gyration(test_sequence)

5450.200714686222

In [25]:
tfe.get_radius_of_gyration(test_sequence_fds)

5421.7724863375815

In [26]:
tfe.get_radius_of_gyration(test_sequence_s)

5464.2820177023395

In [27]:
tfe.get_unc_entropy(test_sequence)

2.5545851693377997

In [28]:
tfe.get_random_entropy(test_sequence)

2.3219280948873622

In [29]:
tfe.get_frequence_regularity(test_sequence)

4

In [30]:
tfe.get_entropy(test_sequence)

2.5216406363433181

In [31]:
chronology = tfe.get_chronology(test_sequence,latlong1[0],latlong1[1])
data_days_window = 1
window = data_days_window*24*60 # 8 dias en minutos

In [32]:
tfe.get_regularity(chronology,window)

/home/cata/anaconda2/lib/python2.7/site-packages/scipy/integrate/quadpack.py:352: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  warnings.warn(msg, IntegrationWarning)


1.6020952049349486

## Testing de parametro de clustering

### Usuario 0

In [33]:
tfe.get_latlong_points(test_sequence_0)

[array([[-33.52627673, -70.63555144],
        [-33.43411554, -70.64810407],
        [-33.40597083, -70.59837899],
        [-33.52915693, -70.63529341],
        [-33.40370241, -70.5959504 ]]),
 ['T-22-205-SN-65',
  'E-20-291-PO-20',
  'T-15-135-OP-110',
  'T-22-205-SN-55',
  'T-15-135-OP-105'],
 [0.38461538461538464,
  0.07692307692307693,
  0.38461538461538464,
  0.07692307692307693,
  0.07692307692307693]]

In [34]:
tfe.get_clusters(test_sequence_0)

array([1, 3, 2, 1, 2], dtype=int32)

In [35]:
tfe.get_ROIs(test_sequence_0,0.6)

[[{'lat': -33.527716828857699, 'long': -70.63542242496419},
  {'lat': -33.404836618443298, 'long': -70.59716469585355}],
 0.92307692307692313]

### Usuario 5

In [36]:
tfe.get_latlong_points(test_sequence_5)

[array([[-33.45538012, -70.59435763],
        [-33.445905  , -70.572037  ],
        [-33.446474  , -70.6605    ],
        [-33.38088497, -70.63959576],
        [-33.45392058, -70.60820951]]),
 ['T-18-157-PO-60',
  'SIMON BOLIVAR',
  'LOS HEROES',
  'T-3-19-NS-45',
  'T-18-157-PO-40'],
 [0.07692307692307693,
  0.3076923076923077,
  0.46153846153846156,
  0.07692307692307693,
  0.07692307692307693]]

In [37]:
tfe.get_clusters(test_sequence_5)

array([1, 2, 3, 4, 1], dtype=int32)

### Usuario 1187

In [38]:
tfe.get_latlong_points(test_sequence_1187)

[array([[-33.445905, -70.572037],
        [-33.445088, -70.654635],
        [-33.418227, -70.60145 ],
        [-33.442848, -70.645809]]),
 ['SIMON BOLIVAR', 'LA MONEDA', 'TOBALABA', 'SANTA LUCIA'],
 [0.4166666666666667,
  0.4166666666666667,
  0.08333333333333333,
  0.08333333333333333]]

In [39]:
tfe.get_clusters(test_sequence_1187)

array([2, 1, 3, 1], dtype=int32)

### Usuario 9

In [40]:
tfe.get_latlong_points(test_sequence_9)

[array([[-33.58569792, -70.56792786],
        [-33.426222  , -70.590972  ],
        [-33.425466  , -70.614272  ],
        [-33.437258  , -70.650551  ],
        [-33.35325793, -70.73862841],
        [-33.3661621 , -70.69038151],
        [-33.58878935, -70.56735882],
        [-33.42337652, -70.60534444]]),
 ['L-34-58-SN-75',
  'CRISTOBAL COLON',
  'PEDRO DE VALDIVIA',
  'PLAZA DE ARMAS',
  'L-6-44-SN-15',
  'T-2-7-PO-6',
  'L-34-58-SN-85',
  'T-14-124-PO-5'],
 [0.25,
  0.25,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333]]

In [41]:
tfe.get_clusters(test_sequence_9)

array([1, 5, 4, 6, 2, 3, 1, 4], dtype=int32)

In [42]:
tfe.get_ROIs(test_sequence_9,0.6)

[[{'lat': -33.587243636232401, 'long': -70.567643341586745},
  {'lat': -33.426222000000003, 'long': -70.590971999999994},
  {'lat': -33.424421262438649, 'long': -70.609808218859499}],
 0.74999999999999989]

### Usuario 2168

In [43]:
tfe.get_latlong_points(test_sequence_2168)

[array([[-33.51969653, -70.69566673],
        [-33.408     , -70.555597  ],
        [-33.52220722, -70.69737383],
        [-33.51585164, -70.69392295]]),
 ['T-29-238-SN-15',
  'HERNANDO DE MAGALLANES',
  'T-29-238-SN-10',
  'T-29-238-NS-15'],
 [0.36363636363636365,
  0.45454545454545453,
  0.09090909090909091,
  0.09090909090909091]]

In [44]:
tfe.get_clusters(test_sequence_2168)

array([1, 2, 1, 1], dtype=int32)

In [45]:
tfe.get_ROIs(test_sequence_2168,0.6)

[[{'lat': -33.519251799763197, 'long': -70.695654501591832},
  {'lat': -33.408000000000001, 'long': -70.555597000000006}],
 1.0]

In [46]:
chronology

[405.73333333333335,
 2704.983333333333,
 4141.35,
 5579.233333333334,
 7016.8,
 10482.116666666667]

In [47]:
window

1440

In [48]:
chronology = tfe.get_chronology(test_sequence_2168,-33.408,-70.555597)
tfe.get_regularity(chronology,window*1)

59.69041525755263

### Usuario 3696

In [49]:
tfe.get_latlong_points(test_sequence_3696)

[array([[-33.491584  , -70.617529  ],
        [-33.5968712 , -70.56581313],
        [-33.52824548, -70.58893172],
        [-33.52617858, -70.58906619],
        [-33.59713105, -70.56879213]]),
 ['CAMINO AGRICOLA',
  'L-34-70-OP-85',
  'L-33-23-OP-50',
  'L-33-9-NS-5',
  'L-34-70-OP-75'],
 [0.5384615384615384,
  0.07692307692307693,
  0.23076923076923078,
  0.07692307692307693,
  0.07692307692307693]]

In [50]:
tfe.get_clusters(test_sequence_3696)

array([3, 1, 2, 2, 1], dtype=int32)

In [51]:
tfe.get_ROIs(test_sequence_3696,0.6)

[[{'lat': -33.491584000000003, 'long': -70.617529000000005},
  {'lat': -33.527212030973004, 'long': -70.588998953262049}],
 0.84615384615384615]

### Usuario 4150

In [52]:
tfe.get_latlong_points(test_sequence_4150)

[array([[-33.60973119, -70.52173709],
        [-33.56950568, -70.5831589 ],
        [-33.60212   , -70.577195  ],
        [-33.60957101, -70.52156182],
        [-33.60800907, -70.52317261]]),
 ['L-34-37-PO-20',
  'L-34-52-PO-5',
  'LAS MERCEDES',
  'L-34-114-NS-5',
  'L-34-2-OP-50'],
 [0.09090909090909091,
  0.45454545454545453,
  0.09090909090909091,
  0.18181818181818182,
  0.18181818181818182]]

In [53]:
tfe.get_clusters(test_sequence_4150)

array([1, 2, 3, 1, 1], dtype=int32)

In [54]:
tfe.get_ROIs(test_sequence_4150,0.6)

[[{'lat': -33.609103755975731, 'long': -70.522157174440835},
  {'lat': -33.569505683331002, 'long': -70.583158899591695}],
 0.90909090909090906]

In [55]:
chronology = tfe.get_chronology(test_sequence_4150,-33.56950568,-70.5831589)
data_days_window = 1
window = data_days_window*24*60 # 8 dias en minutos
tfe.get_regularity(chronology,window)

1.9834816567142834

In [56]:
# regularity not working!

## Testing Big Function

In [287]:
reload(borrador)
reload(tfe)

<module 'tfe' from 'tfe.py'>

In [288]:
a = borrador.get_features(test_sequence_0)

In [289]:
assert tfe.get_mean_shortest_activity_length(test_sequence_0) == a[0]
assert tfe.get_mean_longest_activity_length(test_sequence_0) == a[1]
assert tfe.get_traveled_distance(test_sequence_0) == a[2]
assert tfe.get_maximum_travel_distance(test_sequence_0) == a[3]
assert tfe.get_minimum_travel_distance(test_sequence_0) == a[4]
assert tfe.get_radius_of_gyration(test_sequence_0) == a[5]
assert tfe.get_unc_entropy(test_sequence_0) == a[6]
assert tfe.get_random_entropy(test_sequence_0) == a[7]
assert tfe.get_percentage_different_last_origin(test_sequence_0) == a[8]
assert tfe.get_percentage_different_first_origin(test_sequence_0) == a[9]
assert tfe.get_card_type(test_sequence_0) == a[10]
assert tfe.get_mean_start_time_first_trip(test_sequence_0) == a[11]
assert tfe.get_mean_start_time_last_trip(test_sequence_0) == a[12]
assert tfe.get_n_days_traveled(test_sequence_0) == a[13]
assert tfe.get_n_days_traveled_before_stop(test_sequence_0) == a[14]
assert tfe.get_frequence_regularity(test_sequence_0) == a[15]
assert tfe.get_percentage_bus_exclusive_days(test_sequence_0) == a[16]
assert tfe.get_percentage_rail_exclusive_days(test_sequence_0) == a[17]
assert tfe.get_percentage_bus_trips(test_sequence_0) == a[18]

In [290]:
test_sequences = [ test_sequence_5, test_sequence_1187, test_sequence_0, test_sequence_9, test_sequence_2168, test_sequence_3696, test_sequence_4150]

In [291]:
the_vectors = []
for test_seq in test_sequences:
    the_vectors.append(borrador.get_features(test_seq))

In [292]:
counter = 0
for test_seq in test_sequences:
    a = borrador.get_features(test_seq)
    print "Test de ", counter
    assert tfe.get_mean_shortest_activity_length(test_seq) == a[0]
    assert tfe.get_mean_longest_activity_length(test_seq) == a[1]
    assert tfe.get_traveled_distance(test_seq) == a[2]
    assert tfe.get_maximum_travel_distance(test_seq) == a[3]
    assert tfe.get_minimum_travel_distance(test_seq) == a[4]
    assert tfe.get_radius_of_gyration(test_seq) == a[5]
    assert tfe.get_unc_entropy(test_seq) == a[6]
    assert tfe.get_random_entropy(test_seq) == a[7]
    assert tfe.get_percentage_different_last_origin(test_seq) == a[8]
    assert tfe.get_percentage_different_first_origin(test_seq) == a[9]
    assert tfe.get_card_type(test_seq) == a[10]
    assert tfe.get_mean_start_time_first_trip(test_seq) == a[11]
    assert tfe.get_mean_start_time_last_trip(test_seq) == a[12]
    assert tfe.get_n_days_traveled(test_seq) == a[13]
    assert tfe.get_n_days_traveled_before_stop(test_seq) == a[14]
    assert tfe.get_frequence_regularity(test_seq) == a[15]
    assert tfe.get_percentage_bus_exclusive_days(test_seq) == a[16]
    assert tfe.get_percentage_rail_exclusive_days(test_seq) == a[17]
    assert tfe.get_percentage_bus_trips(test_seq) == a[18]
    counter += 1

Test de  0


AssertionError: 

In [293]:
tfe.get_percentage_rail_exclusive_days(test_sequence_5)

50.0

In [294]:
the_vectors[0][17]

0.0

In [286]:
test_sequence_5[['tipo_transporte']]

tipo_transporte
96             BUS
95             BUS
94           METRO
93           METRO
92             BUS
91           METRO
90           METRO
89           METRO
88           METRO
87           METRO
86           METRO
85           METRO
84             BUS
83           METRO
82             BUS
81             BUS

In [ ]:
#TODO fix the bug