In [1]:
import matplotlib.pyplot as plt
import time
import datetime as dt
import pickle
import numpy as np
import borrador
from __future__ import division
from auxiliar_functions import *
import tfe


In [2]:
datos_abril = pd.read_csv('/home/cata/Documentos/Datois/etapas_2013_abril_allyearsids_10_100000.csv')


In [3]:
datos_abril = frame_config(datos_abril)

In [4]:
#frame.drop(frame.columns[[2,3,4,5,9,10,11,14,15,16]], axis=1, inplace=True)
datos_abril.head()

tiempo_subida       id  x_subida  y_subida tipo_transporte  \
23 2013-04-14 06:45:44  1132106    348108   6289153             BUS   
22 2013-04-14 07:51:52  1132106    346751   6299389             BUS   
21 2013-04-14 19:56:47  1132106    351368   6302559             BUS   
20 2013-04-14 20:15:25  1132106    346713   6299427             BUS   
19 2013-04-15 21:04:59  1132106    348103   6289191             BUS   

   serviciosentidovariante tipo_dia  nviaje  netapa  x_bajada  \
23                T203 00R  DOMINGO       1       1    346818   
22                T502 00I  DOMINGO       2       1    351363   
21                T502 00R  DOMINGO       3       1    346763   
20                T203 00I  DOMINGO       3       2    348095   
19                T206 00R  LABORAL       4       1    346844   

          ...              par_bajada zona_subida zona_bajada adulto  weekday  \
23        ...          E-20-190-SN-40         328         307      0        6   
22        ...           T-15-135-PO-5         307         188      0        6   
21        ...           T-4-19-NS-100         188          55      0        6   
20        ...          T-24-205-NS-20         307         348      0        6   
19        ...          T-20-190-SN-35         328         309      0        0   

    lat_subida  lat_bajada  long_subida  long_bajada  diferencia_tiempo  
23  -33.526277  -33.526277   -70.635551   -70.647786    0 days 00:00:00  
22  -33.434116  -33.434116   -70.648104   -70.598251    0 days 01:06:08  
21  -33.405971  -33.405971   -70.598379   -70.648651    0 days 12:04:55  
20  -33.433463  -33.433463   -70.649060   -70.635944    0 days 00:18:38  
19  -33.526277  -33.526277   -70.635551   -70.647429    1 days 00:49:34  

[5 rows x 23 columns]

In [5]:
datos_abril.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 23 to 99994
Data columns (total 23 columns):
tiempo_subida              100000 non-null datetime64[ns]
id                         100000 non-null int64
x_subida                   99224 non-null float64
y_subida                   99224 non-null float64
tipo_transporte            100000 non-null object
serviciosentidovariante    98074 non-null object
tipo_dia                   100000 non-null object
nviaje                     100000 non-null int64
netapa                     100000 non-null int64
x_bajada                   86774 non-null float64
y_bajada                   86774 non-null float64
tiempo_bajada              86774 non-null object
par_subida                 99195 non-null object
par_bajada                 86767 non-null object
zona_subida                99180 non-null float64
zona_bajada                86764 non-null float64
adulto                     86774 non-null float64
weekday                    100000 non-

In [6]:
test_sequence_5 = datos_abril.query('id==1261466')
test_sequence_1187 = datos_abril.query('id==50264508')
test_sequence_0 = datos_abril.query('id==1132106')
test_sequence_9 = datos_abril.query('id==1355530')
test_sequence_2168 = datos_abril.query('id==59460077')
test_sequence_3696 = datos_abril.query('id==68660100')
test_sequence_4150= datos_abril.query('id==70321252')

In [7]:
test_sequence = test_sequence_0
[test_sequence_s ,test_sequence_fds] = tfe.split_sequence_by_weekdays(test_sequence)

In [8]:
shortest_activities_s = tfe.get_mean_shortest_activity_length(test_sequence_s)
longest_activities_s = tfe.get_mean_longest_activity_length(test_sequence_s)
shortest_activities_fds = tfe.get_mean_shortest_activity_length(test_sequence_fds)
longest_activities_fds = tfe.get_mean_longest_activity_length(test_sequence_fds)

In [9]:
print str(shortest_activities_s) + " , " + str(shortest_activities_fds)
print str(longest_activities_s) + " , " + str(longest_activities_fds)

495.8 , 66.0
606.6 , 1456.0


In [10]:
latlong1 = (test_sequence_fds['lat_subida'][0],test_sequence_fds['long_subida'][0])
latlong2 = (test_sequence_fds['lat_bajada'][0],test_sequence_fds['long_bajada'][0])

In [11]:
tfe.get_traveled_distance(test_sequence)

221.22859034150613

In [12]:
tfe.get_maximum_travel_distance(test_sequence)

16.64618851242621

In [13]:
tfe.get_minimum_travel_distance(test_sequence)

1.136515222708523

In [14]:
tfe.get_percentage_bus_exclusive_days(test_sequence)

100.0

In [15]:
tfe.get_percentage_rail_exclusive_days(test_sequence)

0.0

In [16]:
tfe.get_card_type(test_sequence)

0

In [17]:
tfe.get_n_days_traveled(test_sequence)

7

In [18]:
tfe.get_n_trips_per_day(test_sequence)

[3, 1, 2, 2, 2, 1, 0, 2]

In [19]:
tfe.get_mean_start_time_first_trip(test_sequence)

33061

In [20]:
tfe.get_mean_start_time_last_trip(test_sequence)

67229

In [21]:
tfe.get_percentage_different_last_origin(test_sequence)

57.14285714285714

In [22]:
tfe.get_percentage_different_first_origin(test_sequence)

42.857142857142854

In [23]:
tfe.get_n_different_locations(test_sequence)

5

In [24]:
tfe.get_radius_of_gyration(test_sequence)

5450.200714686222

In [25]:
tfe.get_radius_of_gyration(test_sequence_fds)

5421.7724863375815

In [26]:
tfe.get_radius_of_gyration(test_sequence_s)

5464.2820177023395

In [27]:
tfe.get_unc_entropy(test_sequence)

2.5545851693377997

In [28]:
tfe.get_random_entropy(test_sequence)

2.3219280948873622

In [29]:
tfe.get_frequence_regularity(test_sequence)

4

In [30]:
tfe.get_entropy(test_sequence)

2.5216406363433181

In [31]:
chronology = tfe.get_chronology(test_sequence,latlong1[0],latlong1[1])
data_days_window = 1
window = data_days_window*24*60 # 8 dias en minutos

In [32]:
tfe.get_regularity(chronology,window)

/home/cata/anaconda2/lib/python2.7/site-packages/scipy/integrate/quadpack.py:352: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  warnings.warn(msg, IntegrationWarning)


1.6020952049349486

## Testing de parametro de clustering

### Usuario 0

In [33]:
tfe.get_latlong_points(test_sequence_0)

[array([[-33.52627673, -70.63555144],
        [-33.43411554, -70.64810407],
        [-33.40597083, -70.59837899],
        [-33.52915693, -70.63529341],
        [-33.40370241, -70.5959504 ]]),
 ['T-22-205-SN-65',
  'E-20-291-PO-20',
  'T-15-135-OP-110',
  'T-22-205-SN-55',
  'T-15-135-OP-105'],
 [0.38461538461538464,
  0.07692307692307693,
  0.38461538461538464,
  0.07692307692307693,
  0.07692307692307693]]

In [34]:
tfe.get_clusters(test_sequence_0)

array([1, 3, 2, 1, 2], dtype=int32)

In [35]:
tfe.get_ROIs(test_sequence_0,0.6)

[[{'lat': -33.527716828857699, 'long': -70.63542242496419},
  {'lat': -33.404836618443298, 'long': -70.59716469585355}],
 0.92307692307692313]

### Usuario 5

In [36]:
tfe.get_latlong_points(test_sequence_5)

[array([[-33.45538012, -70.59435763],
        [-33.445905  , -70.572037  ],
        [-33.446474  , -70.6605    ],
        [-33.38088497, -70.63959576],
        [-33.45392058, -70.60820951]]),
 ['T-18-157-PO-60',
  'SIMON BOLIVAR',
  'LOS HEROES',
  'T-3-19-NS-45',
  'T-18-157-PO-40'],
 [0.07692307692307693,
  0.3076923076923077,
  0.46153846153846156,
  0.07692307692307693,
  0.07692307692307693]]

In [37]:
tfe.get_clusters(test_sequence_5)

array([1, 2, 3, 4, 1], dtype=int32)

### Usuario 1187

In [38]:
tfe.get_latlong_points(test_sequence_1187)

[array([[-33.445905, -70.572037],
        [-33.445088, -70.654635],
        [-33.418227, -70.60145 ],
        [-33.442848, -70.645809]]),
 ['SIMON BOLIVAR', 'LA MONEDA', 'TOBALABA', 'SANTA LUCIA'],
 [0.4166666666666667,
  0.4166666666666667,
  0.08333333333333333,
  0.08333333333333333]]

In [39]:
tfe.get_clusters(test_sequence_1187)

array([2, 1, 3, 1], dtype=int32)

### Usuario 9

In [40]:
tfe.get_latlong_points(test_sequence_9)

[array([[-33.58569792, -70.56792786],
        [-33.426222  , -70.590972  ],
        [-33.425466  , -70.614272  ],
        [-33.437258  , -70.650551  ],
        [-33.35325793, -70.73862841],
        [-33.3661621 , -70.69038151],
        [-33.58878935, -70.56735882],
        [-33.42337652, -70.60534444]]),
 ['L-34-58-SN-75',
  'CRISTOBAL COLON',
  'PEDRO DE VALDIVIA',
  'PLAZA DE ARMAS',
  'L-6-44-SN-15',
  'T-2-7-PO-6',
  'L-34-58-SN-85',
  'T-14-124-PO-5'],
 [0.25,
  0.25,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333,
  0.08333333333333333]]

In [41]:
tfe.get_clusters(test_sequence_9)

array([1, 5, 4, 6, 2, 3, 1, 4], dtype=int32)

In [42]:
tfe.get_ROIs(test_sequence_9,0.6)

[[{'lat': -33.587243636232401, 'long': -70.567643341586745},
  {'lat': -33.426222000000003, 'long': -70.590971999999994},
  {'lat': -33.424421262438649, 'long': -70.609808218859499}],
 0.74999999999999989]

### Usuario 2168

In [43]:
tfe.get_latlong_points(test_sequence_2168)

[array([[-33.51969653, -70.69566673],
        [-33.408     , -70.555597  ],
        [-33.52220722, -70.69737383],
        [-33.51585164, -70.69392295]]),
 ['T-29-238-SN-15',
  'HERNANDO DE MAGALLANES',
  'T-29-238-SN-10',
  'T-29-238-NS-15'],
 [0.36363636363636365,
  0.45454545454545453,
  0.09090909090909091,
  0.09090909090909091]]

In [44]:
tfe.get_clusters(test_sequence_2168)

array([1, 2, 1, 1], dtype=int32)

In [45]:
tfe.get_ROIs(test_sequence_2168,0.6)

[[{'lat': -33.519251799763197, 'long': -70.695654501591832},
  {'lat': -33.408000000000001, 'long': -70.555597000000006}],
 1.0]

In [46]:
chronology

[405.73333333333335,
 2704.983333333333,
 4141.35,
 5579.233333333334,
 7016.8,
 10482.116666666667]

In [47]:
window

1440

In [48]:
chronology = tfe.get_chronology(test_sequence_2168,-33.408,-70.555597)
tfe.get_regularity(chronology,window*1)

59.69041525755263

### Usuario 3696

In [49]:
tfe.get_latlong_points(test_sequence_3696)

[array([[-33.491584  , -70.617529  ],
        [-33.5968712 , -70.56581313],
        [-33.52824548, -70.58893172],
        [-33.52617858, -70.58906619],
        [-33.59713105, -70.56879213]]),
 ['CAMINO AGRICOLA',
  'L-34-70-OP-85',
  'L-33-23-OP-50',
  'L-33-9-NS-5',
  'L-34-70-OP-75'],
 [0.5384615384615384,
  0.07692307692307693,
  0.23076923076923078,
  0.07692307692307693,
  0.07692307692307693]]

In [50]:
tfe.get_clusters(test_sequence_3696)

array([3, 1, 2, 2, 1], dtype=int32)

In [51]:
tfe.get_ROIs(test_sequence_3696,0.6)

[[{'lat': -33.491584000000003, 'long': -70.617529000000005},
  {'lat': -33.527212030973004, 'long': -70.588998953262049}],
 0.84615384615384615]

### Usuario 4150

In [52]:
tfe.get_latlong_points(test_sequence_4150)

[array([[-33.60973119, -70.52173709],
        [-33.56950568, -70.5831589 ],
        [-33.60212   , -70.577195  ],
        [-33.60957101, -70.52156182],
        [-33.60800907, -70.52317261]]),
 ['L-34-37-PO-20',
  'L-34-52-PO-5',
  'LAS MERCEDES',
  'L-34-114-NS-5',
  'L-34-2-OP-50'],
 [0.09090909090909091,
  0.45454545454545453,
  0.09090909090909091,
  0.18181818181818182,
  0.18181818181818182]]

In [53]:
tfe.get_clusters(test_sequence_4150)

array([1, 2, 3, 1, 1], dtype=int32)

In [54]:
tfe.get_ROIs(test_sequence_4150,0.6)

[[{'lat': -33.609103755975731, 'long': -70.522157174440835},
  {'lat': -33.569505683331002, 'long': -70.583158899591695}],
 0.90909090909090906]

In [55]:
chronology = tfe.get_chronology(test_sequence_4150,-33.56950568,-70.5831589)
data_days_window = 1
window = data_days_window*24*60 # 8 dias en minutos
tfe.get_regularity(chronology,window)

1.9834816567142834

In [56]:
# regularity not working!

## Testing Big Function

In [100]:
test_sequences = [ test_sequence_5, test_sequence_1187, test_sequence_0, test_sequence_9, \
                  test_sequence_2168, test_sequence_3696, test_sequence_4150]
the_vectors = []
for test_seq in test_sequences:
    the_vectors.append(borrador.get_features(test_seq))

In [101]:
counter = 0
ids = [5,1187,0,9,2168,3696,4150]
for test_seq in test_sequences:
    print "Test de ", ids[counter]
    a = borrador.get_features(test_seq)
    assert tfe.get_mean_shortest_activity_length(test_seq) == a[0]
    assert tfe.get_mean_longest_activity_length(test_seq) == a[1]
    assert tfe.get_traveled_distance(test_seq) == a[2]
    assert tfe.get_maximum_travel_distance(test_seq) == a[3]
    assert tfe.get_minimum_travel_distance(test_seq) == a[4]
    assert tfe.get_radius_of_gyration(test_seq) == a[5]
    assert tfe.get_unc_entropy(test_seq) == a[6]
    assert tfe.get_random_entropy(test_seq) == a[7]
    assert tfe.get_percentage_different_last_origin(test_seq) == a[8]
    assert tfe.get_percentage_different_first_origin(test_seq) == a[9]
    assert tfe.get_card_type(test_seq) == a[10]
    assert tfe.get_mean_start_time_first_trip(test_seq) == a[11]
    assert tfe.get_mean_start_time_last_trip(test_seq) == a[12]
    assert tfe.get_n_days_traveled(test_seq) == a[13]
    assert tfe.get_n_days_traveled_before_stop(test_seq) == a[14]
    assert tfe.get_frequence_regularity(test_seq) == a[15]
    assert tfe.get_percentage_bus_exclusive_days(test_seq) == a[16]
    assert tfe.get_percentage_rail_exclusive_days(test_seq) == a[17]
    assert tfe.get_percentage_bus_trips(test_seq) == a[18]
    counter += 1

Test de  5
Test de  1187
Test de  0
Test de  9
Test de  2168
Test de  3696
Test de  4150


## Measuring euclidean distance between vectors

In [60]:
datos_septiembre = pd.read_csv('/home/cata/Documentos/Datois/etapas_2013_septiembre_allyearsids_10_100000.csv')

In [61]:
datos_semptiembre = frame_config(datos_semptiembre)

In [62]:
user_ids = [1261466,50264508,1132106,1355530,59460077,68660100,70321252]

In [63]:
the_dfs = []
for i in user_ids:
    a_str = 'datos_semptiembre.query("id=='+str(i)+'")'
    the_dfs.append(eval(a_str))


In [64]:
septiembre_vectors = []
for test_seq in the_dfs:
    septiembre_vectors.append(borrador.get_features(test_seq))

In [65]:
counter = 0
counteri = 0
a_matrix = np.zeros((7, 7))
for j in ids:
    abril_vector = the_vectors[counter]
    for i in ids:
        septiembre_vector = septiembre_vectors[counteri]
        dist = np.linalg.norm(np.asarray(abril_vector)-np.asarray(septiembre_vector))
        a_matrix[counter,counteri] = dist
        counteri += 1
    counter += 1
    counteri = 0


In [66]:
comparacion = pd.DataFrame(a_matrix)
comparacion.columns = ids
comparacion.index = ids

In [67]:
comparacion

5             1187          0             9             2168  \
5      8698.065499   9215.020121   8318.888476  12369.119785  13987.983062   
1187   4405.479536   1010.542175   3700.352041  12576.240427   4266.490953   
0      6056.313595   3543.371417    652.250216  12923.684821   7715.778219   
9     14014.219853  16864.781561  18601.335710   6830.979660  16109.947142   
2168   9467.923321   7854.094333   9043.102875  14570.023826   4188.467695   
3696  15521.498056  15017.214407  12827.739082  18882.805347  19895.262905   
4150   4163.466705   7700.611540  10458.535257   6315.598113   8620.984540   

              3696          4150  
5      3509.919340   4982.998149  
1187  12574.190350   5596.497994  
0      9775.465495   4819.295210  
9     22420.379524  16448.670519  
2168  18945.486342  11985.784427  
3696   3765.200560  11689.312500  
4150  14475.649278   7061.016367

In [68]:
comparacion[5]

5        8698.065499
1187     4405.479536
0        6056.313595
9       14014.219853
2168     9467.923321
3696    15521.498056
4150     4163.466705
Name: 5, dtype: float64

In [69]:
for i in ids:
    print np.argmin(comparacion[i])

4150
1187
0
4150
2168
5
0


## Measuring distance between vectors (100.000)

In [103]:
reload(borrador)
reload(tfe)

<module 'tfe' from 'tfe.pyc'>

In [76]:
datos_abril.set_index(keys=['id'], drop=False,inplace=True)
# get a list of names
ids_abril=datos_abril['id'].unique().tolist()

datos_septiembre.set_index(keys=['id'],drop=False,inplace=True)
# get a list of names
ids_septiembre = datos_septiembre['id'].unique().tolist()

In [77]:
limit = np.min((len(ids_abril),len(ids_septiembre)))
limit

5169

In [104]:
abril_vectors = []
septiembre_vectors = []
init_time = time.time()
for i in range(limit):
    an_id = ids_abril[i]
    abril_sequence = datos_abril.loc[datos_abril.id==an_id]
    abril_vector = borrador.get_features(abril_sequence)
    abril_vectors.append(abril_vector)
delta_time = time.time()-init_time
print delta_time

69.8989849091


In [105]:
septiembre_vectors = []
init_time = time.time()
for i in range(limit):
    an_id = ids_abril[i]
    septiembre_sequence = datos_septiembre.loc[datos_septiembre.id==an_id]
    septiembre_vector = borrador.get_features(septiembre_sequence)
    septiembre_vectors.append(septiembre_vector)
delta_time = time.time()-init_time
print delta_time

68.1145610809


In [ ]:
a_matrix = np.zeros((limit, limit)) 
init_time = time.time()
for i in range(limit):
    for j in range(limit):
        dist = np.linalg.norm(np.asarray(abril_vectors[i])-np.asarray(septiembre_vectors[j]))
        a_matrix[i,j] = dist
delta_time = time.time()-init_time
print delta_time

In [ ]:
identified_indexs = []
wrong_indexs = []
correct_indexs = []
selected_indexs = []
n_identified = 0
for i in range(limit):
    the_index = np.argmin(iden_matrix[:,i])
    selected_indexs.append(np.max(iden_matrix[:,i]))
    identified_indexs.append(the_index)
    if(the_index!=i):
        wrong_indexs.append(the_index)
    else:
        correct_indexs.append(the_index)
        n_identified += 1
